add_torrent:
  name: Add torrent
  description: Add a new torrent to download (URL, magnet link or Base64 encoded).
  fields:
    name:
      name: Name
      description: Instance name as entered during entry config
      required: true
      example: Transmission
      selector:
        text:
    torrent:
      name: Torrent
      description: URL, magnet link or Base64 encoded file.
      required: true
      example: http://releases.ubuntu.com/19.04/ubuntu-19.04-desktop-amd64.iso.torrent
      selector:
        text:
