add_torrent:
  name: Add torrent
  description: Add a new torrent to download (URL, magnet link or Base64 encoded).
  fields:
    torrent:
      name: Torrent
      description: URL, magnet link or Base64 encoded file.
      required: true
      example: http://releases.ubuntu.com/19.04/ubuntu-19.04-desktop-amd64.iso.torrent
      selector:
        text:
remove_torrent:
  name: Remove torrent
  description: Remove torrent.
  fields:
    torrent:
      name: Torrent Hash
      description: Torrent hash that you want delete
      required: true
      example: Rtorrent
      selector:
        text:
